#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Space\Cli\Build;
use Space\Cli\Delete;
use Space\Cli\Key;
use Space\Cli\Collection;
use Space\Get;

$application = new Application();

$application->add(new Build());
$application->add(new Delete());
$application->add(new Key());
$application->add(new Collection());

$space = Get::Collection('root/core/cli');
if($space!=NULL && count($space)>0)
{
    foreach($space as $key => $value)
        {
            $application->add(new $value());
        }
}

$application->run();