#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Core\Space\Cli\Build;
use Core\Space\Cli\Delete;
use Core\Space\Cli\Key;
use Core\Space\Cli\Collection;

$application = new Application();

$application->add(new Build());
$application->add(new Delete());
$application->add(new Key());
$application->add(new Collection());

$application->run();